const DATA_DUMMY = [
  {
    id: "us1",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ",
    level: "Junior Developer",
    title: "Web Services vs API",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  {
    id: "us2",
    image: "/images/avt-u1.jpeg",
    name: "Lò Văn Lõ 2",
    level: "Junior Developer 2",
    title: "Web Services vs API 2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, quia ratione illo ipsa dolorem non laudantium, ab neque eaque obcaecati reiciendis, nostrum ullam mollitia fugiat accusantium hic. Veniam, error. Beatae.",
    tags: ["webdev", "javascript", "python"],
    reactiontTotal: 20,
    commentTotal: 10,
    timeReader: 2,
  },
  
];

export function getAllPost() {
  return DATA_DUMMY;
}
